name: slack - Notify slack of GitHub Release
description: Notify Slack of GitHub Release.
author: openhousepvt
inputs:
  status:
    description: Specify success, failure, cancelled or a custom status.
    required: true
  channel:
    description: Override default channel with different channel or username
    required: false
  downloadUrl:
    description: Artifact download URL
    required: false
  version:
    description: Artifact version
    required: true
  platform:
    description: Artifact platform
    required: true  
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: alert-circle
  color: red
