name: "custom-test"
on:
  repository_dispatch:
    types: [custom]

jobs:
  custom:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - id: build
      run: |
        npm install
        npm run all
    - uses: ./
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#actions'
        downloadUrl: "https://github.com/openhousepvt"
        version: '1.0.0'
        platform: 'Android'
      if: always()
