name: "manual-test"
on: workflow_dispatch

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - id: build
      run: |
        npm install
        npm run all
    - uses: openhousepvt/slack@v1.3.2
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#actions'
        downloadUrl: "https://github.com/openhousepvt"
        version: '1.0.0'
        platform: 'Android'
      if: always()
