name: "schedule-test"
on:
  schedule:
    - cron:  '0 10 * * *'

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - id: build
      run: |
        npm install
        npm run all
    - uses: ./
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#actions'
        version: '1.0.0'
        platform: 'Android'
      if: always()
