name: "build-test"
on: # rebuild any PRs and main branch changes
  check_run:
  check_suite:
  create:
  delete:
  deployment:
  deployment_status:
  fork:
  gollum:
  issue_comment:
  issues:
  label:
  milestone:
  page_build:
  project:
  project_card:
  project_column:
  public:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  push:
    branches:
      - master
      - 'releases/*'
  registry_package:
  release:
  status:
  watch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - id: build
      run: |
        npm install
        npm run format-check
        npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - id: build
      run: |
        npm install
        npm run all
    - uses: ./
      with:
        status: ${{ job.status }}
        channel: '#actions'
        version: '1.0.0'
        platform: 'Android'
      if: always()